Module2 task1
htmlacademy-vue/2187503-pizza-1 pull request #2
Opened 2022-10-04 15:27 UTC by SMVladimir

Разбивка компонента «Конструктор пиццы» на мелкие компоненты

2022-10-05 04:36 UTC, enotke requested changes

2022-10-05 04:36 UTC, enotke commented on src/frontend/src/builder/components/BuilderIngredientsSelector.vue
> +      this.value.sauceId = sauceId;
Нельзя менять значения props. Нужно использовать события для обновления. Тоже самое в ItemCounter

2022-10-05 04:36 UTC, enotke commented on src/frontend/src/builder/components/BuilderIngredientsSelector.vue
> +      ingredients: [],
А это для чего?

2022-10-05 04:36 UTC, enotke commented on src/frontend/src/builder/components/BuilderPriceCounter.vue
> +        this.getIngredientsPrice() === 0 ||
`return this.getIngredientsPrice() === 0 || this.pizzaName === null || this.pizzaName === ""`

2022-10-05 04:36 UTC, enotke commented on src/frontend/src/common/components/ItemCounter.vue
> +      count: 0,
А зачем это?

2022-10-05 04:36 UTC, enotke commented on src/frontend/src/common/components/ItemCounter.vue
> +      if (this.count === 0) {
Условие срабатывает и поэтому постоянно добавляется объект в массив

2022-10-05 04:36 UTC, enotke commented on src/frontend/src/common/components/ItemCounter.vue
> +      for (var i = 0; i < this.recipe.ingredients.length; i = i + 1) {
Можно использовать `Array.forEach`

2022-10-05 04:37 UTC, enotke commented on src/frontend/src/builder/components/BuilderIngredientsSelector.vue
> +      this.value.sauceId = sauceId;
и BuilderPizzaView. Везде нужно исправить

2022-10-09 07:34 UTC, SMVladimir commented on src/frontend/src/builder/components/BuilderIngredientsSelector.vue
> +      this.value.sauceId = sauceId;
Виталий почему нельзя? Я где-то использовал emit, а где-то v-model. Да и v-model изучается в следующем разделе. Нужно исправить считаете?

2022-10-09 07:36 UTC, SMVladimir commented on src/frontend/src/builder/components/BuilderIngredientsSelector.vue
> +      ingredients: [],
о, я думаю это осталось после рефакторинга))

2022-10-09 07:38 UTC, SMVladimir commented on src/frontend/src/common/components/ItemCounter.vue
> +      for (var i = 0; i < this.recipe.ingredients.length; i = i + 1) {
я научусь и поправлю, спасибо

2022-10-09 07:39 UTC, SMVladimir commented on src/frontend/src/common/components/ItemCounter.vue
> +      if (this.count === 0) {
да, это нужно исправить, спасибо, не уследил, рефакторил по нескольку раз, можно увидеть в коммитах

2022-10-09 07:40 UTC, SMVladimir commented on src/frontend/src/common/components/ItemCounter.vue
> +      count: 0,
это тоже после рефакторинга)

2022-10-13 06:48 UTC, enotke commented on src/frontend/src/builder/components/BuilderIngredientsSelector.vue
> +      this.value.sauceId = sauceId;
V-model это синтаксический сахар. Он же не меняет пропсы напрямую.

2022-10-13 08:45 UTC, merged